name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  firebase_storage: ^12.3.4
  firebase_core: ^3.6.0
  flutter_spinkit: ^5.2.1
  path: ^1.9.0
  http: ^1.2.2
  firebase_app_check: ^0.3.1+4
  http_parser: ^4.0.0
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.4+1
  flutter_dotenv: ^5.0.2
  modal_bottom_sheet: ^3.0.0
  timeline_tile: ^2.0.0
  video_player: ^2.5.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.0.0
  visibility_detector: ^0.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.png"

flutter:
  assets:
    - .env
    - lib/assets/images/

  uses-material-design: true
